version: "3"
services:
  postgres:
    container_name: onlyplanks-va-postgres
    image: postgres:15
    ports:
      - "6031:5432"
    env_file:
      - .docker.env
    volumes:
      - ../onlyplanks-postgres-data:/var/lib/postgresql/data
    networks:
      - app
  minio:
    image: minio/minio
    container_name: onlyplanks-minio-server
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: root1234
    ports:
      - "9030:9000"
      - "9031:9001"
    restart: always
    working_dir: "/minio-image/storage"
    volumes:
      - ../onlyplanks-minio/storage:/minio-image/storage
    command: server /minio-image/storage --console-address :9031
    networks:
      - app
  app:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: onlyplanks-mouse-maps-api
    ports:
      - "8030:8000"
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    depends_on:
      - postgres
      - minio
    networks:
      - app
networks:
  app:
    driver: bridge