version: "3"
services:
  postgres:
    container_name: va-postgres
    image: postgres:15
    ports:
      - "6031:5432"
    env_file:
      - .docker.env
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    networks:
      - app
  minio:
    image: minio/minio
    container_name: minio-server
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: root1234
    ports:
      - "9030:9000"
      - "9031:9001"
    restart: always
    working_dir: "/minio-image/storage"
    volumes:
      - ./Storage/minio/storage:/minio-image/storage
    command: server /minio-image/storage --console-address :9001
    networks:
      - app
networks:
  app:
    driver: bridge